name: Build and Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build voxlink.exe
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoxLink-Windows
          path: target/release/voxlink.exe

  create-release:
    needs: build-windows
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: VoxLink-Windows
          path: ./binaries

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep '^version' Cargo.toml | head -1 | awk -F '"' '{print $2}')
          echo "VERSION=v$VERSION" >> $GITHUB_ENV
          echo "Detected version: v$VERSION"

      - name: Zip the executable
        run: |
          cd binaries
          zip voxlink-windows.zip voxlink.exe
          
      - name: Create or Update Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.VERSION }}"
          prerelease: false
          title: "VoxLink ${{ env.VERSION }}"
          files: |
            ./binaries/voxlink-windows.zip
